name: harry_potter_characters
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 3.0.0
  equatable: ^1.2.6
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
